name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

defaults:
  run:
    shell: 'bash -x {0}'

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:trixie
    steps:
    - uses: actions/checkout@v4
    - name: update sources.list
      run:  |
        apt update && \
        apt dist-upgrade -y && \
        apt install -y \
        sudo \
        curl \
        wget \
        unzip \
        rsync \
        git \
        git-lfs \
        openssl \
        devscripts \
        equivs \
        gawk \
        gnupg2 \
        systemd \
        jq \
        ca-certificates && \
        echo "deb [arch=amd64] http://download.proxmox.com/debian/pve trixie pve-test" > /etc/apt/sources.list.d/pve-no-subscription.list && \
        echo "deb [arch=amd64] http://download.proxmox.com/debian/devel trixie main" > /etc/apt/sources.list.d/pve-devel.list && \
        wget https://enterprise.proxmox.com/debian/proxmox-release-trixie.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-trixie.gpg && \
        apt update && apt dist-upgrade -y

    - name: install tools
      run: sudo apt-get -y install devscripts equivs

    - name: install deps    
      run: sudo mk-build-deps -i < <(yes) || true
            
    - name: run make
      run: make clean && make deb

    - name: List what has been built
      if: ${{ !cancelled() }}
      run: |
          find . -name "*.deb" -o -name "*.buildinfo" -o -name "*.changes" | xargs ls -ld

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: pve-manager
          path: |
           ./*.deb
           ./*.buildinfo
           ./*.changes

    - name: upload-release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./{*.deb,*.buildinfo,*.changes}
          tag: ${{ github.ref }}
          file_glob: true
